services:
  backend:
    build:
      context: ./backend
    container_name: mail-search-backend
    expose:
      - "8080"
    environment:
      APP_EML_ROOT: "/data/documents"
      APP_INDEX_DIR: "/app/data/index"
      APP_DB_PATH: "/app/db/mailsearch"
    volumes:
      - "/data/owncloud/_data/files/admin/files/Documents:/data/documents:ro"
      - backend_index:/app/data/index
      - "./db:/app/db"
    restart: unless-stopped

  frontend:
    build:
      context: ./frontend
    container_name: mail-search-frontend
    ports:
      - "5173:80"
    depends_on:
      - backend
    restart: unless-stopped

volumes:
  backend_index:
