package com.example.mailsearch.service;

import com.example.mailsearch.config.AppProperties;
import com.example.mailsearch.dto.AuthUserResponse;
import jakarta.annotation.PostConstruct;
import org.springframework.jdbc.core.JdbcTemplate;
import org.springframework.security.core.GrantedAuthority;
import org.springframework.security.core.authority.SimpleGrantedAuthority;
import org.springframework.security.core.userdetails.User;
import org.springframework.security.core.userdetails.UserDetails;
import org.springframework.security.core.userdetails.UserDetailsService;
import org.springframework.security.core.userdetails.UsernameNotFoundException;
import org.springframework.security.crypto.password.PasswordEncoder;
import org.springframework.stereotype.Service;

import java.nio.file.Files;
import java.nio.file.Path;
import java.nio.file.Paths;
import java.util.List;

@Service
public class AuthService implements UserDetailsService {
    private final JdbcTemplate jdbcTemplate;
    private final PasswordEncoder passwordEncoder;
    private final AppProperties appProperties;

    public AuthService(JdbcTemplate jdbcTemplate, PasswordEncoder passwordEncoder, AppProperties appProperties) {
        this.jdbcTemplate = jdbcTemplate;
        this.passwordEncoder = passwordEncoder;
        this.appProperties = appProperties;
    }

    @PostConstruct
    public void initialize() throws Exception {
        Path dbPath = Paths.get(appProperties.getDbPath()).toAbsolutePath().normalize();
        Path parent = dbPath.getParent();
        if (parent != null) {
            Files.createDirectories(parent);
        }

        jdbcTemplate.execute("""
                create table if not exists app_user (
                    id bigint generated by default as identity primary key,
                    username varchar(100) not null unique,
                    password_hash varchar(255) not null,
                    role varchar(50) not null,
                    must_change_password boolean default true not null,
                    created_at timestamp default current_timestamp not null
                )
                """);
        jdbcTemplate.execute("alter table app_user add column if not exists must_change_password boolean default true not null");

        Integer count = jdbcTemplate.queryForObject(
                "select count(*) from app_user where username = ?",
                Integer.class,
                appProperties.getAuthUsername()
        );

        if (count == null || count == 0) {
            jdbcTemplate.update(
                    "insert into app_user (username, password_hash, role, must_change_password) values (?, ?, ?, ?)",
                    appProperties.getAuthUsername(),
                    passwordEncoder.encode(appProperties.getAuthPassword()),
                    "ADMIN",
                    true
            );
        } else {
            String passwordHash = jdbcTemplate.queryForObject(
                    "select password_hash from app_user where username = ?",
                    String.class,
                    appProperties.getAuthUsername()
            );
            if (passwordHash != null && (passwordEncoder.matches("admin1234", passwordHash) || passwordEncoder.matches("admin", passwordHash))) {
                jdbcTemplate.update(
                        "update app_user set password_hash = ?, must_change_password = true where username = ?",
                        passwordEncoder.encode(appProperties.getAuthPassword()),
                        appProperties.getAuthUsername()
                );
            }
        }
    }

    public AuthUserResponse getUserProfile(String username) {
        return jdbcTemplate.queryForObject(
                "select username, must_change_password from app_user where username = ?",
                (rs, rowNum) -> new AuthUserResponse(rs.getString("username"), rs.getBoolean("must_change_password")),
                username
        );
    }

    public void changePassword(String username, String newPassword) {
        jdbcTemplate.update(
                "update app_user set password_hash = ?, must_change_password = false where username = ?",
                passwordEncoder.encode(newPassword),
                username
        );
    }

    @Override
    public UserDetails loadUserByUsername(String username) throws UsernameNotFoundException {
        List<UserDetails> users = jdbcTemplate.query(
                "select username, password_hash, role from app_user where username = ?",
                (rs, rowNum) -> {
                    GrantedAuthority authority = new SimpleGrantedAuthority("ROLE_" + rs.getString("role"));
                    return new User(rs.getString("username"), rs.getString("password_hash"), List.of(authority));
                },
                username
        );

        if (users.isEmpty()) {
            throw new UsernameNotFoundException("사용자를 찾을 수 없습니다.");
        }

        return users.get(0);
    }
}
